CREATE DATABASE IF NOT EXISTS library_db;
USE library_db;

CREATE TABLE IF NOT EXISTS book (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(255),
    year INT
);

CREATE TABLE IF NOT EXISTS NguoiDung (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hoTen VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    matKhau VARCHAR(255),
    vaiTro ENUM('DOCGIA', 'THUTHU', 'ADMIN') DEFAULT 'DOCGIA',
    ngayTao DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DauSach (
    maDauSach VARCHAR(20) PRIMARY KEY,
    tenSach VARCHAR(255) NOT NULL,
    tacGia VARCHAR(255),
    theLoai VARCHAR(100),
    nhaXuatBan VARCHAR(255),
    namXuatBan INT,
    moTa TEXT,
    tongSoLuong INT DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BanSaoSach (
    maVach VARCHAR(50) PRIMARY KEY,
    maDauSach VARCHAR(20) NOT NULL,
    trangThai ENUM('CO_SAN', 'DANG_MUON', 'HU_HONG', 'MAT') DEFAULT 'CO_SAN',

    FOREIGN KEY (maDauSach)
        REFERENCES DauSach(maDauSach)
        ON DELETE CASCADE
) ENGINE=InnoDB;